
export const viewsActionTypes = {
    SET_ACTIVE_STORY: 'VIEWS.SET_ACTIVE_STORY',
    SET_ACTIVE_PANEL: 'VIEWS.SET_ACTIVE_PANEL',
    SET_ACTIVE_SCENE: 'VIEWS.SET_ACTIVE_SCENE',
    SET_HISTORY: 'VIEWS.SET_HISTORY',
    SET_NEED_EPIC: 'VIEWS.SET_NEED_EPIC',
    SET_SNACKBAR: 'VIEWS.SET_SNACKBAR',
    SET_POPOUT: 'VIEWS.SET_POPOUT',
    SET_GLOBAL_ERROR: 'VIEWS.SET_GLOBAL_ERROR',
}
export const accountActionTypes = {
    SET_SCHEME: 'ACCOUNT.SET_SCHEME',
}